apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: stackit-git
  namespace: argo
spec:
  template:
    metadata:
      labels:
        networking.gardener.cloud/to-dns: allowed
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    stackit-git-push:
      port: "12000"
      endpoint: /push
      method: POST
