apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: stackit-git-sensor
  namespace: argo
spec:
  template:
    metadata:
      labels:
        networking.gardener.cloud/to-dns: allowed
    serviceAccountName: argo-workflow
  dependencies:
    - name: stackit-git-push
      eventSourceName: stackit-git
      eventName: stackit-git-push
  triggers:
    - template:
        name: trigger-build-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: build-image-
                namespace: argo
              spec:
                serviceAccountName: argo-workflow
                workflowTemplateRef:
                  name: kaniko-build
                arguments:
                  parameters:
                    - name: repo-url
                      value: "git@git.stackit.cloud:YOUR_PROJECT/YOUR_REPO.git"
                    - name: revision
                      value: "main"
                    - name: image-name
                      value: "harbor.example.com/myproject/myapp"
                    - name: image-tag
                      value: "latest"
          parameters:
            - src:
                dependencyName: stackit-git-push
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value
              operation: override
